/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AbrirRouteImport } from './routes/abrir'
import { Route as ChamadosRouteImport } from './routes/chamados'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AbrirRoute = AbrirRouteImport.update({
  id: '/abrir',
  path: '/abrir',
  getParentRoute: () => rootRouteImport,
} as any)
const ChamadosRoute = ChamadosRouteImport.update({
  id: '/chamados',
  path: '/chamados',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abrir': typeof AbrirRoute
  '/chamados': typeof ChamadosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abrir': typeof AbrirRoute
  '/chamados': typeof ChamadosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abrir': typeof AbrirRoute
  '/chamados': typeof ChamadosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/abrir' | '/chamados'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/abrir' | '/chamados'
  id: '__root__' | '/' | '/abrir' | '/chamados'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbrirRoute: typeof AbrirRoute
  ChamadosRoute: typeof ChamadosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abrir': {
      id: '/abrir'
      path: '/abrir'
      fullPath: '/abrir'
      preLoaderRoute: typeof AbrirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chamados': {
      id: '/chamados'
      path: '/chamados'
      fullPath: '/chamados'
      preLoaderRoute: typeof ChamadosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbrirRoute: AbrirRoute,
  ChamadosRoute: ChamadosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
