/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AbrirRouteImport } from './routes/abrir'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAtendimentoRouteImport } from './routes/_authenticated/atendimento'
import { Route as AuthenticatedChamadosRouteImport } from './routes/_authenticated/chamados'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedRegrasRouteImport } from './routes/_authenticated/regras'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AbrirRoute = AbrirRouteImport.update({
  id: '/abrir',
  path: '/abrir',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAtendimentoRoute =
  AuthenticatedAtendimentoRouteImport.update({
    id: '/atendimento',
    path: '/atendimento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChamadosRoute = AuthenticatedChamadosRouteImport.update({
  id: '/chamados',
  path: '/chamados',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRegrasRoute = AuthenticatedRegrasRouteImport.update({
  id: '/regras',
  path: '/regras',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abrir': typeof AbrirRoute
  '/auth': typeof AuthRoute
  '/atendimento': typeof AuthenticatedAtendimentoRoute
  '/chamados': typeof AuthenticatedChamadosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/regras': typeof AuthenticatedRegrasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abrir': typeof AbrirRoute
  '/auth': typeof AuthRoute
  '/atendimento': typeof AuthenticatedAtendimentoRoute
  '/chamados': typeof AuthenticatedChamadosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/regras': typeof AuthenticatedRegrasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/abrir': typeof AbrirRoute
  '/auth': typeof AuthRoute
  '/_authenticated/atendimento': typeof AuthenticatedAtendimentoRoute
  '/_authenticated/chamados': typeof AuthenticatedChamadosRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/regras': typeof AuthenticatedRegrasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/abrir'
    | '/auth'
    | '/atendimento'
    | '/chamados'
    | '/dashboard'
    | '/regras'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/abrir'
    | '/auth'
    | '/atendimento'
    | '/chamados'
    | '/dashboard'
    | '/regras'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/abrir'
    | '/auth'
    | '/_authenticated/atendimento'
    | '/_authenticated/chamados'
    | '/_authenticated/dashboard'
    | '/_authenticated/regras'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AbrirRoute: typeof AbrirRoute
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abrir': {
      id: '/abrir'
      path: '/abrir'
      fullPath: '/abrir'
      preLoaderRoute: typeof AbrirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/atendimento': {
      id: '/_authenticated/atendimento'
      path: '/atendimento'
      fullPath: '/atendimento'
      preLoaderRoute: typeof AuthenticatedAtendimentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chamados': {
      id: '/_authenticated/chamados'
      path: '/chamados'
      fullPath: '/chamados'
      preLoaderRoute: typeof AuthenticatedChamadosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/regras': {
      id: '/_authenticated/regras'
      path: '/regras'
      fullPath: '/regras'
      preLoaderRoute: typeof AuthenticatedRegrasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAtendimentoRoute: typeof AuthenticatedAtendimentoRoute
  AuthenticatedChamadosRoute: typeof AuthenticatedChamadosRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedRegrasRoute: typeof AuthenticatedRegrasRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAtendimentoRoute: AuthenticatedAtendimentoRoute,
  AuthenticatedChamadosRoute: AuthenticatedChamadosRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedRegrasRoute: AuthenticatedRegrasRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AbrirRoute: AbrirRoute,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
